# Generated by Django 4.2.14 on 2024-07-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
